Add support for object_lock_enabled
infrablocks/terraform-aws-encrypted-bucket pull request #38
Opened 2022-12-07 15:54 UTC by cmateiasmypulse

2022-12-07 16:17 UTC, jonassvalin commented
Overall the change looks good, but there are two things that I'm unsure about which I want to clarify before we merge it in.

1. This is a minor thing, but we seem to be setting it to a default value of false now, which seems contrary to what we discussed on Slack (i.e, "null" instead and defer to the default value of AWS).
2. This is a slightly larger question, should the "aws_s3_bucket_object_lock_configuration" that must be created if you enable this flag be created manually outside of the module or actually be part of the module? There's a similar module to this which indeed does it like that: https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/main.tf#L324-L338


Currently there are multiple resources in this module that get created conditionally, such as the bucket_logging, bucket_versioning and public_access_block. This leads me to believe that this would be better suited as being a conditional resource within the module instead. Thoughts?

2022-12-07 16:25 UTC, JDurstberger commented
Yes, you are right on point 1. Our bad. 

I think you might be right on the second point too.
We'll look into that and how we should provide then the variables for the lock config.

2022-12-08 13:34 UTC, jonassvalin requested changes

2022-12-08 13:34 UTC, jonassvalin commented on spec/unit/bucket_spec.rb
> +    it 'creates bucket object lock configuration' do
should be "does NOT create..."

2022-12-08 13:46 UTC, cmateiasmypulse commented on spec/unit/bucket_spec.rb
> +    it 'creates bucket object lock configuration' do
Your're right, updated it.

2022-12-08 13:47 UTC, jonassvalin approved these changes

2022-12-08 13:48 UTC, merged